// Fichier unique des données - Tous les mots du jeu
// Format: { hint: "indice", cat: ID }
// IDs: 1=Animaux, 2=Nourriture, 3=Nature, 4=Véhicules, 5=Nombres, 6=Temps,
//      7=Émotions, 8=Personnages, 9=Corps, 10=Maison, 11=Couleurs, 12=Objets, 13=Sports, 99=Divers

const GAME_DATA = {
    // ============ ANIMAUX (1) ============
    "chat": { hint: "🐱 Animal de compagnie ronronnant", cat: 1 },
    "ours": { hint: "🐻 Gros animal poilu", cat: 1 },
    "lion": { hint: "🦁 Roi de la jungle", cat: 1 },
    "loup": { hint: "🐺 Animal sauvage qui hurle", cat: 1 },
    "élan": { hint: "🦌 Grand cerf du nord", cat: 1 },
    "lapin": { hint: "🐰 Animal aux longues oreilles", cat: 1 },
    "cochon": { hint: "🐷 Animal rose qui grogne", cat: 1 },
    "mouton": { hint: "🐑 Animal avec de la laine", cat: 1 },
    "canard": { hint: "🦆 Oiseau aquatique", cat: 1 },
    "poule": { hint: "🐔 Oiseau de basse-cour", cat: 1 },
    "souris": { hint: "🐭 Petit rongeur gris", cat: 1 },
    "panda": { hint: "🐼 Ours noir et blanc qui mange du bambou", cat: 1 },
    "tigre": { hint: "🐅 Gros chat sauvage rayé", cat: 1 },
    "aigle": { hint: "🦅 Oiseau de proie très grand", cat: 1 },
    "zèbre": { hint: "🦓 Cheval sauvage avec des rayures", cat: 1 },
    "chien": { hint: "🐶 Meilleur ami de l'homme", cat: 1 },
    "tortue": { hint: "🐢 Animal avec une carapace dure", cat: 1 },
    "requin": { hint: "🦈 Poisson dangereux des mers", cat: 1 },
    "renard": { hint: "🦊 Animal rusé et orange", cat: 1 },
    "girafe": { hint: "🦒 Animal très grand avec un long cou", cat: 1 },
    "baleine": { hint: "🐋 Très gros animal marin", cat: 1 },
    "chameau": { hint: "🐪 Animal du désert avec des bosses", cat: 1 },
    "abeille": { hint: "🐝 Insecte qui fait du miel", cat: 1 },
    "papillon": { hint: "🦋 Insecte coloré qui vole", cat: 1 },
    "éléphant": { hint: "🐘 Très gros animal avec une trompe", cat: 1 },
    "dauphin": { hint: "🐬 Animal marin intelligent et joueur", cat: 1 },
    "pingouin": { hint: "🐧 Oiseau qui ne vole pas, nage bien", cat: 1 },
    "dinosaure": { hint: "🦕 Animal géant préhistorique", cat: 1 },
    "kangourou": { hint: "🦘 Animal qui saute avec une poche", cat: 1 },
    "crocodile": { hint: "🐊 Reptile avec de grandes dents", cat: 1 },
    "hippopotame": { hint: "🦛 Très gros animal qui vit dans l'eau", cat: 1 },
    "perroquet": { hint: "🦜 Oiseau coloré qui peut parler", cat: 1 },
    "coccinelle": { hint: "🐞 Petite bête rouge avec des points noirs", cat: 1 },
    "panthère": { hint: "🐆 Grand chat noir très rapide", cat: 1 },
    "pieuvre": { hint: "🐙 Animal marin avec 8 tentacules", cat: 1 },
    
    // ============ NOURRITURE (2) ============
    "pain": { hint: "🥖 Aliment de base fait avec de la farine", cat: 2 },
    "lait": { hint: "🥛 Boisson blanche des vaches", cat: 2 },
    "thé": { hint: "🍵 Boisson chaude", cat: 2 },
    "sel": { hint: "🧂 Pour donner du goût", cat: 2 },
    "noix": { hint: "🌰 Fruit à coque", cat: 2 },
    "miel": { hint: "🍯 Fait par les abeilles", cat: 2 },
    "burger": { hint: "🍔 Sandwich rond avec de la viande", cat: 2 },
    "frites": { hint: "🍟 Pommes de terre frites", cat: 2 },
    "glace": { hint: "🍦 Dessert froid et sucré", cat: 2 },
    "bonbon": { hint: "🍭 Sucrerie colorée", cat: 2 },
    "orange": { hint: "🍊 Fruit orange et rond", cat: 2 },
    "pizza": { hint: "🍕 Plat italien rond avec du fromage et de la tomate", cat: 2 },
    "banane": { hint: "🍌 Fruit jaune et courbé", cat: 2 },
    "gâteau": { hint: "🎂 Dessert sucré", cat: 2 },
    "pomme": { hint: "🍎 Fruit rouge ou vert", cat: 2 },
    "poire": { hint: "🍐 Fruit vert en forme de goutte", cat: 2 },
    "raisin": { hint: "🍇 Petits fruits en grappe", cat: 2 },
    "cerise": { hint: "🍒 Petit fruit rouge", cat: 2 },
    "fraise": { hint: "🍓 Fruit rouge avec des graines", cat: 2 },
    "citron": { hint: "🍋 Fruit jaune et acide", cat: 2 },
    "melon": { hint: "🍈 Gros fruit vert ou orange", cat: 2 },
    "tomate": { hint: "🍅 Fruit rouge pour la sauce", cat: 2 },
    "salade": { hint: "🥗 Légumes verts", cat: 2 },
    "radis": { hint: "🌶️ Petit légume rose", cat: 2 },
    "poivre": { hint: "🌶️ Épice qui pique", cat: 2 },
    "sucre": { hint: "🍬 Rend les choses sucrées", cat: 2 },
    "farine": { hint: "🌾 Poudre pour faire du pain", cat: 2 },
    "huile": { hint: "🫒 Liquide pour cuisiner", cat: 2 },
    "beurre": { hint: "🧈 Produit laitier à tartiner", cat: 2 },
    "yaourt": { hint: "🥛 Produit laitier onctueux", cat: 2 },
    "viande": { hint: "🥩 Chair d'animal", cat: 2 },
    "poulet": { hint: "🍗 Viande de poule", cat: 2 },
    "jambon": { hint: "🥓 Viande de porc", cat: 2 },
    "soupe": { hint: "🍲 Plat liquide chaud", cat: 2 },
    "repas": { hint: "🍽️ Moment où on mange", cat: 2 },
    "carotte": { hint: "🥕 Légume orange que les lapins adorent", cat: 2 },
    "chocolat": { hint: "🍫 Friandise brune et sucrée", cat: 2 },
    "fromage": { hint: "🧀 Produit laitier préféré des souris", cat: 2 },
    "spaghetti": { hint: "🍝 Pâtes longues et fines d'Italie", cat: 2 },
    "sandwich": { hint: "🥪 Pain avec quelque chose dedans", cat: 2 },
    "biscuit": { hint: "🍪 Petit gâteau croquant et sucré", cat: 2 },
    "popcorn": { hint: "🍿 Maïs qui éclate en mangeant", cat: 2 },
    "crêperie": { hint: "🥞 Restaurant qui sert des crêpes", cat: 2 },
    "gâteaux": { hint: "🎂 Plusieurs desserts d'anniversaire", cat: 2 },
    "confiture": { hint: "🍓 Fruits écrasés et sucrés à tartiner", cat: 2 },
    
    // ============ NATURE (3) ============
    "eau": { hint: "💧 Liquide transparent et vital", cat: 3 },
    "air": { hint: "💨 Ce qu'on respire", cat: 3 },
    "mer": { hint: "🌊 Grande étendue d'eau salée", cat: 3 },
    "lac": { hint: "🏞️ Eau douce entourée de terre", cat: 3 },
    "île": { hint: "🏝️ Terre entourée d'eau", cat: 3 },
    "feu": { hint: "🔥 Flammes chaudes", cat: 3 },
    "lune": { hint: "🌙 Astre qui brille la nuit dans le ciel", cat: 3 },
    "parc": { hint: "🌳 Espace vert en ville", cat: 3 },
    "nid": { hint: "🪹 Maison des oiseaux", cat: 3 },
    "volcan": { hint: "🌋 Montagne qui crache du feu", cat: 3 },
    "espace": { hint: "🚀 Zone vide entre les planètes et étoiles", cat: 3 },
    "forêt": { hint: "🌲 Grande étendue d'arbres", cat: 3 },
    "nuage": { hint: "☁️ Vapeur d'eau dans le ciel", cat: 3 },
    "terre": { hint: "🌍 Planète où nous vivons", cat: 3 },
    "plage": { hint: "🏖️ Bord de mer avec du sable", cat: 3 },
    "océan": { hint: "🌊 Grande étendue d'eau salée", cat: 3 },
    "soleil": { hint: "☀️ Étoile qui brille le jour", cat: 3 },
    "étoile": { hint: "⭐ Lumière dans le ciel la nuit", cat: 3 },
    "jardin": { hint: "🌻 Espace avec des fleurs et plantes", cat: 3 },
    "fleur": { hint: "🌸 Plante colorée et parfumée", cat: 3 },
    "arbre": { hint: "🌳 Grande plante avec un tronc", cat: 3 },
    "herbe": { hint: "🌿 Plante verte au sol", cat: 3 },
    "pluie": { hint: "🌧️ Eau qui tombe du ciel", cat: 3 },
    "neige": { hint: "❄️ Flocons blancs en hiver", cat: 3 },
    "nuages": { hint: "☁️ Masses blanches dans le ciel", cat: 3 },
    "saison": { hint: "🍂 Période de l'année", cat: 3 },
    "hiver": { hint: "❄️ Saison froide", cat: 3 },
    "été": { hint: "☀️ Saison chaude", cat: 3 },
    "tempête": { hint: "⛈️ Mauvais temps avec vent et pluie", cat: 3 },
    "rivière": { hint: "🌊 Cours d'eau qui coule", cat: 3 },
    "lumière": { hint: "💡 Ce qui éclaire et rend visible", cat: 3 },
    "montagne": { hint: "⛰️ Grande élévation de terre très haute", cat: 3 },
    "tonnerre": { hint: "⚡ Bruit fort pendant l'orage", cat: 3 },
    "arcenciel": { hint: "🌈 Arc avec toutes les couleurs après la pluie", cat: 3 },
    "palmier": { hint: "🌴 Arbre tropical avec noix de coco", cat: 3 },
    "coquillage": { hint: "🐚 Maison des escargots de mer", cat: 3 },
    "cascade": { hint: "💦 Eau qui tombe de très haut", cat: 3 },
    "étoiles": { hint: "✨ Lumières qui brillent la nuit", cat: 3 },
    "planète": { hint: "🪐 Grosse boule dans l'espace", cat: 3 },
    
    // ============ VÉHICULES (4) ============
    "vélo": { hint: "🚲 Véhicule à 2 roues", cat: 4 },
    "bus": { hint: "🚌 Grand véhicule public", cat: 4 },
    "auto": { hint: "🚗 Autre mot pour voiture", cat: 4 },
    "taxi": { hint: "🚕 Voiture qu'on loue", cat: 4 },
    "moto": { hint: "🏍️ Deux roues motorisé", cat: 4 },
    "avion": { hint: "✈️ Véhicule qui vole", cat: 4 },
    "bateau": { hint: "⛵ Véhicule qui flotte sur l'eau", cat: 4 },
    "train": { hint: "🚂 Véhicule sur des rails", cat: 4 },
    "téléphone": { hint: "📱 Appareil pour appeler et jouer", cat: 4 },
    "ordinateur": { hint: "💻 Machine pour travailler et jouer", cat: 4 },
    "voiture": { hint: "🚗 Véhicule à 4 roues", cat: 4 },
    "hélicoptère": { hint: "🚁 Avion avec une hélice sur le toit", cat: 4 },
    "tracteur": { hint: "🚜 Gros véhicule de la ferme", cat: 4 },
    
    // ============ NOMBRES (5) ============
    "un": { hint: "1️⃣ Premier nombre", cat: 5 },
    "deux": { hint: "2️⃣ Nombre après un", cat: 5 },
    "cinq": { hint: "5️⃣ Le nombre entre 4 et 6", cat: 5 },
    "six": { hint: "6️⃣ Six", cat: 5 },
    "sept": { hint: "7️⃣ Sept", cat: 5 },
    "huit": { hint: "8️⃣ Huit", cat: 5 },
    "neuf": { hint: "9️⃣ Neuf", cat: 5 },
    "dix": { hint: "🔟 Dix", cat: 5 },
    "onze": { hint: "1️⃣1️⃣ Onze", cat: 5 },
    "zéro": { hint: "0️⃣ Rien, le nombre nul", cat: 5 },
    "trois": { hint: "3️⃣ Trois", cat: 5 },
    "quatre": { hint: "4️⃣ Quatre", cat: 5 },
    "douze": { hint: "🔢 Douze (12)", cat: 5 },
    "treize": { hint: "🔢 Treize (13)", cat: 5 },
    "quinze": { hint: "🔢 Quinze (15)", cat: 5 },
    "seize": { hint: "🔢 Seize (16)", cat: 5 },
    "vingt": { hint: "🔢 Vingt (20)", cat: 5 },
    "dix-sept": { hint: "🔢 Dix-sept (17)", cat: 5 },
    "dix-huit": { hint: "🔢 Dix-huit (18)", cat: 5 },
    "dix-neuf": { hint: "🔢 Dix-neuf (19)", cat: 5 },
    "quatorze": { hint: "🔢 (14)", cat: 5 },
    
    // ============ TEMPS (6) ============
    "mai": { hint: "🌸 Mois du printemps", cat: 6 },
    "août": { hint: "☀️ Mois des vacances", cat: 6 },
    "nuit": { hint: "🌙 Quand il fait noir", cat: 6 },
    "jour": { hint: "☀️ Quand il fait clair", cat: 6 },
    "lundi": { hint: "📅 Premier jour de la semaine", cat: 6 },
    "mardi": { hint: "📅 Deuxième jour de la semaine", cat: 6 },
    "jeudi": { hint: "📅 Quatrième jour de la semaine", cat: 6 },
    "samedi": { hint: "📅 Sixième jour de la semaine", cat: 6 },
    "avril": { hint: "🌸 Quatrième mois de l'année", cat: 6 },
    "février": { hint: "❄️ Deuxième mois de l'année", cat: 6 },
    "décembre": { hint: "❄️ Douzième mois de l'année", cat: 6 },
    "mercredi": { hint: "📅 Troisième jour de la semaine", cat: 6 },
    "vendredi": { hint: "📅 Cinquième jour de la semaine", cat: 6 },
    "dimanche": { hint: "📅 Jour de repos", cat: 6 },
    "janvier": { hint: "❄️ Premier mois de l'année", cat: 6 },
    "juillet": { hint: "☀️ Septième mois de l'année", cat: 6 },
    "septembre": { hint: "🍂 Neuvième mois de l'année", cat: 6 },
    "octobre": { hint: "🍂 Dixième mois de l'année", cat: 6 },
    "novembre": { hint: "🍂 Onzième mois de l'année", cat: 6 },
    
    // ============ ÉMOTIONS (7) ============
    "rage": { hint: "😡 Sentiment de colère", cat: 7 },
    "peur": { hint: "😰 Sentiment d'angoisse", cat: 7 },
    "joie": { hint: "😊 Sentiment de bonheur", cat: 7 },
    "paix": { hint: "☮️ Absence de guerre et de conflit", cat: 7 },
    "rire": { hint: "😄 Faire ha ha ha", cat: 7 },
    "amour": { hint: "❤️ Sentiment très fort qu'on a pour quelqu'un", cat: 7 },
    "espoir": { hint: "🌟 Sentiment d'espoir pour l'avenir", cat: 7 },
    "amitié": { hint: "🤝 Relation d'amour entre amis", cat: 7 },
    "bonheur": { hint: "😊 Sentiment de grande joie", cat: 7 },
    "courage": { hint: "💪 Force face à la peur", cat: 7 },
    "sourire": { hint: "😊 Expression du visage qui montre la joie", cat: 7 },
    "heureux": { hint: "😄 Sentiment de grande joie et de bonheur", cat: 7 },
    "tendresse": { hint: "💕 Sentiment doux et affectueux", cat: 7 },
    
    // ============ PERSONNAGES (8) ============
    "bob": { hint: "🏗️ Éponge qui vit dans un ananas", cat: 8 },
    "buzz": { hint: "🚀 Astronaute de Toy Story", cat: 8 },
    "roi": { hint: "👑 Chef d'un royaume", cat: 8 },
    "papa": { hint: "👨 Le père", cat: 8 },
    "fils": { hint: "👦 Garçon de la famille", cat: 8 },
    "bébé": { hint: "👶 Très jeune enfant", cat: 8 },
    "ange": { hint: "😇 Créature céleste", cat: 8 },
    "ninja": { hint: "🥷 Guerrier masqué qui se déplace en silence", cat: 8 },
    "dragon": { hint: "🐉 Créature magique qui vole et crache du feu", cat: 8 },
    "prince": { hint: "🤴 Fils du roi, héros des contes de fées", cat: 8 },
    "reine": { hint: "👸 Femme puissante qui dirige un royaume", cat: 8 },
    "héros": { hint: "🦸 Personne courageuse qui sauve les autres", cat: 8 },
    "pirate": { hint: "🏴‍☠️ Aventurier des mers avec un bandeau sur l'œil", cat: 8 },
    "batman": { hint: "🦇 Super-héros noir de Gotham", cat: 8 },
    "tarzan": { hint: "🦍 Homme de la jungle", cat: 8 },
    "simba": { hint: "🦁 Lion roi de Disney", cat: 8 },
    "woody": { hint: "🤠 Cowboy de Toy Story", cat: 8 },
    "mickey": { hint: "🐭 Souris célèbre de Disney", cat: 8 },
    "sorcier": { hint: "🧙 Homme sage qui connaît tous les sorts", cat: 8 },
    "magicien": { hint: "🧙 Personne qui pratique la magie", cat: 8 },
    "princesse": { hint: "👸 Fille du roi et de la reine", cat: 8 },
    "monstre": { hint: "👹 Créature effrayante et dangereuse", cat: 8 },
    "spiderman": { hint: "🕷️ Super-héros qui grimpe aux murs", cat: 8 },
    "superman": { hint: "🦸 Super-héros qui vole", cat: 8 },
    "aladdin": { hint: "🧞 Jeune homme avec une lampe magique", cat: 8 },
    "chevalier": { hint: "⚔️ Guerrier courageux qui protège les gens", cat: 8 },
    "pinocchio": { hint: "🤥 Pantin en bois dont le nez grandit quand il ment", cat: 8 },
    "cendrillon": { hint: "👗 Princesse qui perd sa pantoufle de verre", cat: 8 },
    "raiponce": { hint: "💇‍♀️ Princesse avec des cheveux très très longs", cat: 8 },
    "pocahontas": { hint: "🍃 Princesse indienne qui aime la nature", cat: 8 },
    "ironman": { hint: "🦾 Super-héros avec armure de fer rouge", cat: 8 },
    "captain": { hint: "🛡️ America - super-héros avec bouclier", cat: 8 },
    
    // ============ CORPS (9) ============
    "oeil": { hint: "👁️ Pour voir", cat: 9 },
    "main": { hint: "✋ Avec cinq doigts", cat: 9 },
    "pied": { hint: "🦶 Pour marcher", cat: 9 },
    "bras": { hint: "💪 Entre épaule et main", cat: 9 },
    "tête": { hint: "🧠 Contient le cerveau", cat: 9 },
    "nez": { hint: "👃 Pour sentir les odeurs", cat: 9 },
    "dos": { hint: "↩️ Arrière du corps", cat: 9 },
    "muscle": { hint: "💪 Partie du corps qui donne la force", cat: 9 },
    "santé": { hint: "❤️ État de bien-être", cat: 9 },
    "corps": { hint: "🧍 Ensemble du physique", cat: 9 },
    "visage": { hint: "😊 Partie avant de la tête", cat: 9 },
    "cheveux": { hint: "💇 Poils sur la tête", cat: 9 },
    "barbe": { hint: "🧔 Poils sur le visage", cat: 9 },
    "dents": { hint: "🦷 Pour mâcher la nourriture", cat: 9 },
    "langue": { hint: "👅 Pour goûter", cat: 9 },
    "jambe": { hint: "🦵 Pour marcher et courir", cat: 9 },
    "doigt": { hint: "👆 Partie de la main", cat: 9 },
    "ongle": { hint: "💅 Bout dur du doigt", cat: 9 },
    "genou": { hint: "🦵 Articulation de la jambe", cat: 9 },
    "coude": { hint: "💪 Articulation du bras", cat: 9 },
    "épaule": { hint: "🤷 Haut du bras", cat: 9 },
    "ventre": { hint: "🤰 Partie du corps avec l'estomac", cat: 9 },
    "cœur": { hint: "❤️ Organe qui bat dans la poitrine", cat: 9 },
    "poumon": { hint: "🫁 Pour respirer", cat: 9 },
    "cerveau": { hint: "🧠 Organe pour penser", cat: 9 },
    "squelette": { hint: "💀 Tous les os du corps assemblés", cat: 9 },
    "estomac": { hint: "🫃 Organe qui digère la nourriture", cat: 9 },
    
    // ============ MAISON (10) ============
    "mur": { hint: "🧱 Paroi d'une maison", cat: 10 },
    "lit": { hint: "🛏️ Meuble pour dormir", cat: 10 },
    "sac": { hint: "🎒 Pour transporter des affaires", cat: 10 },
    "bol": { hint: "🥣 Pour manger la soupe", cat: 10 },
    "clé": { hint: "🔑 Ouvre les portes", cat: 10 },
    "porte": { hint: "🚪 Pour entrer", cat: 10 },
    "maison": { hint: "🏠 Endroit où on habite", cat: 10 },
    "table": { hint: "🪑 Meuble pour manger", cat: 10 },
    "chaise": { hint: "🪑 Meuble pour s'asseoir", cat: 10 },
    "bureau": { hint: "🖥️ Meuble pour travailler", cat: 10 },
    "lampe": { hint: "💡 Pour éclairer", cat: 10 },
    "miroir": { hint: "🪞 Pour se regarder", cat: 10 },
    "rideau": { hint: "🪟 Cache la fenêtre", cat: 10 },
    "tapis": { hint: "🧶 Sur le sol", cat: 10 },
    "coussin": { hint: "🛋️ Objet moelleux pour s'asseoir", cat: 10 },
    "armoire": { hint: "🚪 Meuble pour ranger les vêtements", cat: 10 },
    "étagère": { hint: "📚 Meuble pour ranger les livres", cat: 10 },
    "hôpital": { hint: "🏥 Lieu où on soigne les malades", cat: 10 },
    "cuisine": { hint: "🍳 Pièce où on prépare les repas", cat: 10 },
    "chambre": { hint: "🛏️ Pièce où on dort", cat: 10 },
    "fenêtre": { hint: "🪟 Ouverture pour voir dehors", cat: 10 },
    "escalier": { hint: "🪜 Pour monter et descendre les étages", cat: 10 },
    
    // ============ COULEURS (11) ============
    "vert": { hint: "🌿 Couleur de l'herbe et des feuilles", cat: 11 },
    "couleur": { hint: "🎨 Teinte, nuance", cat: 11 },
    "rouge": { hint: "🔴 Couleur du sang", cat: 11 },
    "jaune": { hint: "🟡 Couleur du soleil", cat: 11 },
    "blanc": { hint: "⚪ Couleur de la neige", cat: 11 },
    "violet": { hint: "🟣 Couleur entre rouge et bleu", cat: 11 },
    "marron": { hint: "🟤 Couleur du bois", cat: 11 },
    
    // ============ OBJETS (12) ============
    "arc": { hint: "🏹 Arme qui lance des flèches très loin", cat: 12 },
    "épée": { hint: "⚔️ Arme brillante et pointue des chevaliers", cat: 12 },
    "phare": { hint: "🗼 Tour qui guide les bateaux", cat: 12 },
    "cage": { hint: "🔒 Prison pour animaux", cat: 12 },
    "livre": { hint: "📚 Objet avec des pages à lire", cat: 12 },
    "étoile": { hint: "⭐ Petite lumière qui scintille dans le ciel", cat: 12 },
    "trésor": { hint: "💰💎 Richesse cachée que tout le monde cherche", cat: 12 },
    "cristal": { hint: "💎 Pierre précieuse et brillante", cat: 12 },
    "château": { hint: "🏰 Grande maison fortifiée des rois", cat: 12 },
    "couronne": { hint: "👑 Bijou doré que portent les rois et reines", cat: 12 },
    "parapluie": { hint: "☂️ Objet pour se protéger de la pluie", cat: 12 },
    "balançoire": { hint: "🎪 Jeu qui se balance dans les airs", cat: 12 },
    "toboggan": { hint: "🛝 Glissade amusante au parc", cat: 12 },
    "trampoline": { hint: "🤸 Pour sauter très haut et rebondir", cat: 12 },
    "télévision": { hint: "📺 Appareil pour regarder des dessins animés", cat: 12 },
    
    // ============ SPORTS (13) ============
    "ski": { hint: "⛷️ Sport d'hiver sur la neige", cat: 13 },
    "foot": { hint: "⚽ Sport avec un ballon", cat: 13 },
    "golf": { hint: "⛳ Sport avec balle et trous", cat: 13 },
    "boxe": { hint: "🥊 Sport de combat", cat: 13 },
    "sport": { hint: "⚽ Activité physique", cat: 13 },
    "ballon": { hint: "⚽ Objet rond pour jouer", cat: 13 },
    "match": { hint: "🏆 Compétition sportive", cat: 13 },
    "tennis": { hint: "🎾 Sport avec raquette", cat: 13 },
    "rugby": { hint: "🏉 Sport avec ballon ovale", cat: 13 },
    "course": { hint: "🏃 Courir vite", cat: 13 },
    "natation": { hint: "🏊 Sport dans l'eau", cat: 13 },
    "football": { hint: "⚽ Sport le plus populaire au monde", cat: 13 },
    "basketball": { hint: "🏀 Sport avec panier et ballon orange", cat: 13 },
    "gymnastique": { hint: "🤸 Sport avec acrobaties et souplesse", cat: 13 },
    
    // ============ DIVERS (99) ============
    "rêve": { hint: "💭 Pensée qui vient quand on dort", cat: 99 },
    "fée": { hint: "🧚 Petite créature magique avec des ailes", cat: 99 },
    "ami": { hint: "🤝 Personne qu'on aime bien", cat: 99 },
    "jeu": { hint: "🎮 Activité amusante", cat: 99 },
    "voie": { hint: "🛣️ Chemin ou route", cat: 99 },
    "pont": { hint: "🌉 Pour traverser l'eau", cat: 99 },
    "tour": { hint: "🗼 Très haut bâtiment", cat: 99 },
    "fin": { hint: "🏁 Terminé", cat: 99 },
    "voyage": { hint: "✈️ Long voyage vers un endroit", cat: 99 },
    "robot": { hint: "🤖 Machine intelligente qui peut bouger et parler", cat: 99 },
    "magie": { hint: "✨ Art mystérieux qui fait apparaître des choses", cat: 99 },
    "super": { hint: "🦸 Mot qui rend tout plus fort et plus cool", cat: 99 },
    "école": { hint: "🏫 Lieu où on apprend", cat: 99 },
    "radio": { hint: "📻 Pour écouter de la musique", cat: 99 },
    "musique": { hint: "🎵 Sons agréables et harmonieux", cat: 99 },
    "chant": { hint: "🎤 Musique avec la voix", cat: 99 },
    "danse": { hint: "💃 Bouger en rythme", cat: 99 },
    "photo": { hint: "📷 Image capturée", cat: 99 },
    "dessin": { hint: "🎨 Image faite à la main", cat: 99 },
    "petit": { hint: "📏 Pas grand", cat: 99 },
    "grand": { hint: "📏 Très haut", cat: 99 },
    "mince": { hint: "📏 Pas épais", cat: 99 },
    "court": { hint: "📏 Petite distance", cat: 99 },
    "rapide": { hint: "⚡ Très vite", cat: 99 },
    "faible": { hint: "😔 Pas fort", cat: 99 },
    "chaud": { hint: "🔥 Haute température", cat: 99 },
    "froid": { hint: "🧊 Basse température", cat: 99 },
    "famille": { hint: "👨‍👩‍👧‍👦 Papa, maman et les enfants ensemble", cat: 99 },
    "mystère": { hint: "🔍 Énigme mystérieuse à résoudre", cat: 99 },
    "magique": { hint: "🎩 Pouvoir surnaturel qui fait des miracles", cat: 99 },
    "aventure": { hint: "🗺️ Voyage excitant plein de découvertes", cat: 99 },
    "liberté": { hint: "🕊️ Droit de faire ce qu'on veut", cat: 99 },
    "courageux": { hint: "💪 Qualité de quelqu'un qui n'a pas peur", cat: 99 },
    "fantôme": { hint: "👻 Créature blanche qui traverse les murs", cat: 99 },
    "licorne": { hint: "🦄 Cheval magique avec une corne", cat: 99 },
    "rigolote": { hint: "😂 Très drôle, qui fait rire", cat: 99 },
    "surprise": { hint: "🎁 Chose inattendue qui fait plaisir", cat: 99 },
    "vacances": { hint: "🏖️ Période sans école pour s'amuser", cat: 99 },
    "histoire": { hint: "📖 Récit qu'on raconte ou lit", cat: 99 },
    "gentillesse": { hint: "😊 Qualité de quelqu'un qui est gentil", cat: 99 },
    "champion": { hint: "🏆 Gagnant d'une compétition", cat: 99 }
};

// Export pour utilisation dans d'autres fichiers
if (typeof module !== 'undefined' && module.exports) {
    module.exports = GAME_DATA;
}
